name: Semgrep Analysis

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 14 * * 0'

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config=p/r2c-ci --json | tee semgrep-results.json

    - name: Upload Semgrep results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-results
        path: semgrep-results.json
