name: Semgrep Analysis with HTML Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 14 * * 0'

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Semgrep
      run: pip install semgrep

    - name: Run Semgrep
      run: semgrep --config=p/r2c-ci --json | tee semgrep-results.json

    - name: Install Python packages for processing
      run: pip install jinja2

    - name: Convert JSON results to HTML
      run: python .github/scripts/convert_to_html.py

    - name: Upload Semgrep results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: semgrep-html-report
        path: semgrep-report.html
