name: Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'javascript'  # Use 'javascript' for Shell scripts; CodeQL uses this for Shell script analysis

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Upload CodeQL results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: codeql-results
        path: codeql-results/**/*.sarif
