name: Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'ruby'  # Specify other languages as needed, separated by commas

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Upload CodeQL results as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: codeql-results
        path: codeql-results/**/*.sarif

    - name: Convert CodeQL results to HTML (Example step)
      run: |
        # Example placeholder command, replace with your actual conversion tool/script
        echo "<html><body><h1>CodeQL Analysis Results</h1><pre>$(cat codeql-results/**/*.sarif)</pre></body></html>" > codeql-results.html

    - name: Upload HTML report as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: codeql-html-report
        path: codeql-results.html
