name: Comprehensive Security Vulnerability Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Generate Reports
      run: |
        import pandas as pd

        # Define the data
        data = {
          "File": [
            "Dockerfile", "Dockerfile", 
            "daemonset.yaml", "daemonset.yaml", "daemonset.yaml", "daemonset.yaml", "daemonset.yaml", 
            "deployment.yaml", "deployment.yaml"
          ],
          "Issue": [
            "Outdated zlib package", "Systemd vulnerability",
            "Privileged container", "Docker socket mount", "Host network usage", "Host PID namespace", "Host IPC namespace",
            "Privileged container", "Docker socket mount"
          ],
          "Severity": [
            "Critical", "High",
            "High", "High", "Medium", "Medium", "Medium",
            "High", "High"
          ],
          "Details": [
            "zlib/zlib1g@1:1.2.13.dfsg-1 is outdated.", "systemd/libsystemd0@252.22-1~deb12u1 is vulnerable.",
            "Container runs with elevated privileges.", "Container has access to the Docker daemon socket.", "Container uses hostNetwork.", "Container shares the host's PID namespace.", "Container uses host's IPC.",
            "Container runs with elevated privileges.", "Container has access to the Docker daemon socket."
          ],
          "Line": [
            "N/A", "N/A",
            "23", "55", "26", "22", "22",
            "23", "55"
          ],
          "Suggestion": [
            "Update to a newer zlib version.", "Update to a secure systemd version.",
            "Set 'privileged: false'.", "Remove mount of Docker daemon socket.", "Set 'hostNetwork: false'.", "Set 'hostPID: false'.", "Set 'hostIPC: false'.",
            "Set 'privileged: false'.", "Remove mount of Docker daemon socket."
          ]
        }

        # Create DataFrame
        df = pd.DataFrame(data)

        # Generate HTML report
        html_report = df.to_html(index=False)
        with open('vulnerability_report.html', 'w') as f:
            f.write(html_report)

        # Generate CSV report
        df.to_csv('vulnerability_report.csv', index=False)

      shell: python

    - name: Upload HTML Report
      uses: actions/upload-artifact@v2
      with:
        name: HTML-Vulnerability-Report
        path: vulnerability_report.html

    - name: Upload CSV Report
      uses: actions/upload-artifact@v2
      with:
        name: CSV-Vulnerability-Report
        path: vulnerability_report.csv
