name: Generate Comprehensive Security Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Generate Report
      run: |
        import csv
        import json
        import os

        # Sample data mimicking vulnerabilities detected in Dockerfile and Kubernetes YAMLs
        vulnerabilities = [
          {"file": "Dockerfile", "issue": "Outdated zlib package", "severity": "Critical", "details": "zlib/zlib1g@1:1.2.13.dfsg-1 is outdated.", "line": "N/A", "suggestion": "Update to the latest zlib package."},
          {"file": "Dockerfile", "issue": "Outdated libsystemd", "severity": "High", "details": "systemd/libsystemd0@252.22-1~deb12u1 is outdated.", "line": "N/A", "suggestion": "Update to the latest systemd package."},
          {"file": "daemonset.yaml", "issue": "Privileged container", "severity": "High", "details": "Container is running with elevated privileges.", "line": "23", "suggestion": "Consider removing 'privileged: true' or restrict its usage."},
          {"file": "daemonset.yaml", "issue": "Docker socket mount", "severity": "High", "details": "Container has access to the Docker daemon socket.", "line": "55", "suggestion": "Avoid mounting Docker socket inside containers."},
          {"file": "deployment.yaml", "issue": "Host network usage", "severity": "Medium", "details": "Container is using hostNetwork.", "line": "26", "suggestion": "Consider not using the host's network namespace unless necessary."},
          # Add additional entries here
        ]

        # Generate HTML report
        html_content = "<html><head><style>table { width: 100%; border-collapse: collapse; } th, td { border: 1px solid black; padding: 8px; } th { background-color: #f2f2f2; }</style></head><body>"
        html_content += "<h1>Security Report</h1><table><tr><th>File</th><th>Issue</th><th>Severity</th><th>Details</th><th>Line</th><th>Suggestion</th></tr>"
        
        for vuln in vulnerabilities:
            html_content += f"<tr><td>{vuln['file']}</td><td>{vuln['issue']}</td><td>{vuln['severity']}</td><td>{vuln['details']}</td><td>{vuln['line']}</td><td>{vuln['suggestion']}</td></tr>"
        
        html_content += "</table></body></html>"
        with open('combined_security_report.html', 'w') as file:
            file.write(html_content)

      shell: python

    - name: Upload Combined Report
      uses: actions/upload-artifact@v2
      with:
        name: Combined-Security-Report
        path: combined_security_report.html
